name: Release
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Remove java api for scala2.11
        if: ${{ matrix.scala == '2.11.12' }}
        run: |
          rm -R src/main/java/space/controlnet/lightioc/api
          rm -R src/test/java
      - uses: olafurpg/setup-scala@v10
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
